hwi_oauth:
    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        keycloak:
            type:                keycloak
            base_url:            '%env(OAUTH_URL)%'
            realm:               '%env(OAUTH_REALM_NAME)%'
            client_id:           '%env(OAUTH_ID)%'
            client_secret:       '%env(OAUTH_SECRET)%'
            options:
                csrf:               true
                refresh_on_expire:  true