security:
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        oauth_provider:
            id: App\Security\OAuthUserProvider
        user_provider:
            entity:
                class: 'App\Entity\User'
                property: 'username'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin/
            oauth:
                resource_owners:
                    keycloak: "/admin/login/check-keycloak"
                login_path:   /admin/login
                use_forward:  false
                failure_path: /admin/login
                default_target_path: /admin
                check_path: /admin/login_check

                oauth_user_provider:
                    service: App\Security\OAuthUserProvider
                provider: oauth_provider

            logout:
                path: /admin/logout
                target: /admin/login
        api:
            pattern: ^/v2/
            stateless: true
            provider: user_provider
            custom_authenticator:
                - App\Security\ApiKeyAuthenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api, roles: PUBLIC_ACCESS } # Temporarily supporting access to API v1
        - { path: ^/v2/health, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/connect, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
