vich_uploader:
    db_driver: orm
    storage:   flysystem

    mappings:
        assets:
            uri_prefix:         '%env(AWS_PUBLIC_URL)%/assets'
            upload_destination: 'oneup_flysystem.assets_filesystem'
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true