name: Deploy Site on push
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
      env:
        fail-fast: true

    - name: Get the latest code
      uses: actions/checkout@v3
      
    - name: Make .env
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Composer Install
      run: composer install --ansi --prefer-dist --no-interaction --no-progress --no-dev

    - name: Check the Symfony console
      run: php bin/console -V

    - name: Copying files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "./"
        target: ${{ secrets.TARGET }}

    - name: Executing Doctrine Migrations
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script:  |
          php bin/console doctrine:migrations:migrate
          php bin/console cache:clear
      
